리뷰 유저 권한 추가 및 리뷰 생성 로직 변경
grooteogi/backend pull request #113
Opened 2022-05-19 08:22 UTC by dldmsql

## Description
리뷰 수정 혹은 삭제 시, 유저 권한 확인 로직 추가

리뷰 생성 로직 변경

리뷰 수정 로직 변경 ( 매퍼 사용 )

2022-05-19 08:32 UTC, Jeonghun-Ban requested changes

2022-05-19 08:32 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/repository/ReservationRepository.java
> +  Optional<Reservation> findByUncanceled(@Param("id") Integer id);
findUncanceledById로 메서드명 변경해주세요

2022-05-19 08:32 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/repository/ReservationRepository.java
> +  Optional<Reservation> findByUncanceled(@Param("id") Integer id);
날짜 비교는 서비스에서 진행해주세요

2022-05-19 08:32 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/repository/ReservationRepository.java
> +  Optional<Reservation> findByIdUncanceled(@Param("reservationId") Integer reservationId);
함수 위에 커멘트 단 거랑 합쳐주세요

2022-05-21 08:04 UTC, dldmsql commented on api/src/main/java/grooteogi/repository/ReservationRepository.java
> +  Optional<Reservation> findByUncanceled(@Param("id") Integer id);
수정했습니다.

2022-05-21 10:02 UTC, Jeonghun-Ban requested changes

2022-05-21 10:42 UTC, Jeonghun-Ban approved these changes
수고하셨습니다

2022-05-21 10:42 UTC, merged