feat : filter post search by heart and review
grooteogi/backend pull request #118
Opened 2022-05-19 19:59 UTC by chobinee

## Related Issue
[Feat] GRTG-269 포스트 검색 API 필터링
## Description
- 전체 포스트와 검색한 포스트 default 값은 기존에 사용 중이던 '최신순'이다.

- 전체 포스트 인기순 (찜 개수 순) 필터링 *findAllByHeart
> PostRepository에서 post와 heart table join 후 heart table에 등록된 post 개수 순으로 post를 불러온다.
- 전체 포스트 리뷰순 (리뷰 개수 순) 필터링 *findAllByReview
> PostRepository에서 post와 review table join 후 review table에 등록된 post 개수 순으로 post를 불러온다.
- 검색한 포스트 인기순 (찜 개수 순) 필터링 *findBySearchAndHeart
> PostRepository에서 post와 heart table join 후 heart table에 등록된 post 개수 순으로 검색한 post를 불러온다.
- 검색한 포스트 리뷰순 (리뷰 개수 순) 필터링 *findBySearchAndReview
> PostRepository에서 post와 review table join 후 review table에 등록된 post 개수 순으로 검색한 post를 불러온다.
## Changes
- PostService 내 searchAllPosts method에서 sort가 null 값으로 들어올 때 기본값 date로 지정 후 switch case 문을 이용하여 sort 값에 따른 필터링 진행
- PostService 내 searchPosts method에서 sort가 null 값으로 들어올 때 기본값 date로 지정 후 switch case 문을 이용하여 sort 값과 검색 키워드에 따른 필터링 진행
- PostRepository 내 existsByUser가 가장 아래쪽에 있었는데 메소드들이 많이 추가 되어 지저분할 것 같아서 가장 위로 위치 변경
## Note

1. PostRepository에 heart와 review filtering하는 query가 비슷한데 parameter로 받아서 처리할 수 없는가?
없다. jpa query문에서 parameter를 받을 때 조건절에서만 사용 가능하다. 시도해봤지만 table 명으로 사용할 수 없었다.
2. PostRepository에서 새로 만든 쿼리들 select 문에 저렇게 post column들을 전부 명시하면 더럽지 않은가? 서브쿼리로 돌릴 수 없을까?
이것 또한 시도해봤지만 서브쿼리 내에서 order by문을 동작 시켜도 메인 쿼리로 넘어오지 않아 필터링이 불가능하다. 혹시 다른 방법이 있다면 알려주시면 정말 감사하겠습니다...

> heart는 테스트 해봤는데 review는 postman으로 reservation post하는 것부터 실패해서 테스트 못해봤습니다... 하지만 heart와 비슷하게 동작하니 문제 없지 않을까 싶습니다. 빠른 시일 내에 테스트해보겠습니다...

2022-05-21 11:13 UTC, jongwooo requested changes
Comment 위주로 살펴봐주세요!

2022-05-21 11:13 UTC, jongwooo commented on api/src/main/java/grooteogi/service/PostService.java
> +    Optional<Post> weqwe = this.postRepository.findById(postId);
필요없는 코드는 삭제 부탁드립니다!

2022-05-21 11:13 UTC, jongwooo commented on api/src/main/java/grooteogi/service/PostService.java
>  }
newline 추가 부탁드립니다!

2022-05-22 10:49 UTC, Jeonghun-Ban approved these changes
수고하셨습니다

2022-05-22 10:49 UTC, merged