포스트 검색 시, region 조건 추가
grooteogi/backend pull request #125
Opened 2022-05-21 08:40 UTC by dldmsql

## Description
기존 `search()` param에서 region 조건 추가

2022-05-22 10:17 UTC, Jeonghun-Ban commented
region enum을 추가해두면 좋을 거 같습니다.

2022-05-23 02:39 UTC, Jeonghun-Ban requested changes

2022-05-23 02:39 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/enums/RegionType.java
> +  public static RegionType valueOfLabel(String label) {
그냥 `valueOf` 메서드를 오버라이딩하는건 어떨까요??

2022-05-23 02:39 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/enums/RegionType.java
> +  public String getLabel() {
`toString`을 오버라이딩해서 사용해도 좋을 거 같습니다.

2022-05-23 02:40 UTC, jongwooo requested changes
전체적으로 가독성이 높은 코드라 리뷰하기 편했습니다. Comment 위주로 살펴봐주세요~

2022-05-23 02:40 UTC, jongwooo commented on api/src/main/java/grooteogi/enums/RegionType.java
> +}
newline 추가해주세요

2022-05-23 02:40 UTC, jongwooo commented on api/src/main/java/grooteogi/enums/RegionType.java
> +    for (RegionType regionType : values()) {
Stream의 매칭 메서드를 사용해보는 것도 좋은 방법입니다! 아래의 블로그 글을 참고하여 개선해보세요.

[https://cornswrold.tistory.com/300](https://cornswrold.tistory.com/300)

2022-05-23 03:28 UTC, dldmsql commented on api/src/main/java/grooteogi/enums/RegionType.java
> +    for (RegionType regionType : values()) {
매칭 메서드의 return 타입이 boolean인데, front에서 넘어오는 데이터가 enum에 존재하는지의 여부만 확인하라는 뜻인가요??

2022-05-23 03:30 UTC, dldmsql commented on api/src/main/java/grooteogi/enums/RegionType.java
> +  public static RegionType valueOfLabel(String label) {
`valueOf` 메서드를 오버라이딩 하면, 
![image](https://user-images.githubusercontent.com/61505572/169737883-6f6d47e5-3b6b-4888-a1a7-46022cedaa93.png)
다음과 같은 에러가 발생해서 `valueOfLable`를 따로 두었습니다.!
오버라이딩 하라는 의미를 제가 잘못 이해했을까요..?

2022-05-23 03:40 UTC, dldmsql commented on api/src/main/java/grooteogi/enums/RegionType.java
> +  public String getLabel() {
리뷰 남겨주신 대로 수정했습니다.

2022-05-23 04:34 UTC, jongwooo commented on api/src/main/java/grooteogi/enums/RegionType.java
> +    for (RegionType regionType : values()) {
다른 것이랑 헷갈렸네요.

[https://codechacha.com/ko/java8-stream-difference-findany-findfirst/](https://codechacha.com/ko/java8-stream-difference-findany-findfirst/)를 보시면 될 것 같습니다!

2022-05-23 04:37 UTC, Jeonghun-Ban requested changes

2022-05-23 04:37 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/enums/RegionType.java
> +  public static RegionType valueOfLabel(String label) {
https://localcoder.org/override-valueof-and-tostring-in-java-enum

여기 4번째 솔루션 참고해주세요

2022-05-23 04:51 UTC, jongwooo approved these changes
고생하셨습니다~

2022-05-23 04:51 UTC, Jeonghun-Ban approved these changes
깔끔하게 잘 작성해주셨네요. 수고 많으셨습니다!

2022-05-23 04:51 UTC, merged