Post, Reservation API 변경
grooteogi/backend pull request #162
Opened 2022-05-28 12:18 UTC by kyuriiii

## Related Issue
[GRTG-344](https://babiyak.atlassian.net/browse/GRTG-344)

## Description
Post 와 Reservation API 를 테스트하며 정해진 DTO와 다르거나 로직이 작동하지 않는 코드들 수정

2022-05-28 14:59 UTC, Jeonghun-Ban requested changes

2022-05-28 14:59 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
> +  CANNOT_APPLY_RESERVATION_EXCEPTION(HttpStatus.CONFLICT, "신청 불가능한 일정입니다."),
일정이 아니라 예약 중복인 경우 같은데 메시지 수정하는게 좋을 거 같네요.
그리고 enum 네이밍 같은 경우는 이전처럼 RESERVATION_DUPLICATE_EXCEPTION으로 하는게 좋아 보입니다.

2022-05-28 15:02 UTC, jongwooo requested changes
Comment 위주로 살펴봐주세요.

2022-05-29 01:27 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/exception/ApiExceptionEnum.java
> +  CANNOT_APPLY_RESERVATION_EXCEPTION(HttpStatus.CONFLICT, "신청 불가능한 일정입니다."),
`SCHEDULE_APPLY_FAIL_EXCEPTION`으로 변경해주세요

2022-05-29 01:32 UTC, Jeonghun-Ban approved these changes
수고하셨습니다.

2022-05-29 01:35 UTC, jongwooo approved these changes

2022-05-29 01:36 UTC, merged