feat: Add send sms api
grooteogi/backend pull request #96
Opened 2022-05-12 05:20 UTC by winterdeisy

## Related Issue
add send sns api

## Description
spring에서 핸드폰으로 인증문자 보내기

## Changes

## Note

2022-05-12 05:42 UTC, jongwooo requested changes
Comment 위주로 살펴봐주시면 좋을 것 같아요!

2022-05-12 05:42 UTC, jongwooo commented on api/src/main/java/grooteogi/dto/ReservationDto.java
>  }
newline 추가 부탁드려요!

2022-05-12 05:42 UTC, jongwooo commented on api/src/main/java/grooteogi/controller/ReservationController.java
> +    for (int i = 0; i < 4; i++) {
아래의 블로그 글을 참고하시어 파이프라인으로 구성해보시는 것을 추천드립니다!

[https://jeonghun-ban.github.io/posts/java/refactoring-loops-to-collection-pipelines/](https://jeonghun-ban.github.io/posts/java/refactoring-loops-to-collection-pipelines/)

2022-05-12 05:45 UTC, jongwooo commented on api/src/main/java/grooteogi/controller/ReservationController.java
> +    for (int i = 0; i < 4; i++) {
아래 링크의 방법도 좋은 방법이니 참고해보시면 좋을 것 같아요!

[https://stackoverflow.com/questions/33577737/how-to-generate-a-random-long-with-4-digits-in-java](https://stackoverflow.com/questions/33577737/how-to-generate-a-random-long-with-4-digits-in-java)

2022-05-14 10:51 UTC, Jeonghun-Ban approved these changes

2022-05-15 14:55 UTC, Jeonghun-Ban approved these changes

2022-05-15 14:55 UTC, merged