feat: Create review API
grooteogi/backend pull request #99
Opened 2022-05-14 11:10 UTC by kyuriiii

## Related Issue
[GRTG-263 리뷰API](https://babiyak.atlassian.net/browse/GRTG-263)

## Description
리뷰 API 제작

2022-05-15 15:00 UTC, Jeonghun-Ban requested changes

2022-05-16 00:08 UTC, kyuriiii commented on api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
> +  ACCESS_TOKEN_EXPIRATION_TIME("JWT 만료 시간 / 30분", 1000L * 60 * 10), // * 30 추가 필요 현재 테스트를 위해 1분으로 설정
기존 시간이 테스트를 위해 1분으로 짧게 설정된 거였습니다!

2022-05-16 00:32 UTC, kyuriiii commented on api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
> +  ACCESS_TOKEN_EXPIRATION_TIME("JWT 만료 시간 / 30분", 1000L * 60 * 10), // * 30 추가 필요 현재 테스트를 위해 1분으로 설정
그래도 다시 변경해놓을까요?

2022-05-16 05:58 UTC, Jeonghun-Ban requested changes

2022-05-16 05:58 UTC, Jeonghun-Ban commented on api/src/main/java/grooteogi/enums/JwtExpirationEnum.java
> +  ACCESS_TOKEN_EXPIRATION_TIME("JWT 만료 시간 / 30분", 1000L * 60 * 10), // * 30 추가 필요 현재 테스트를 위해 1분으로 설정
네네 원래대로 해주시는 게 좋을 거 같아요

2022-05-16 08:37 UTC, Jeonghun-Ban approved these changes
수고하셨습니다.

2022-05-16 08:37 UTC, merged